### ISSUE TITLE
When will the training code and pre-trained model be released?

### ISSUE THREAD

**Issue by KevinGoodman** [leonnnop/VAR#2]
Thank you for sharing the dataset. I wonder when the the training code and pre-trained model for REASONER will be released.

**Comment by PeterBishop0** [comment]
I am also looking forward to reproducing your wonderful work! @leonnnop

**Comment by leonnnop** [comment]
Thanks for your interest in VAR. The code is released. Feel free to reopen this thread or open a new thread if you have further questions.
