### ISSUE TITLE
A question about temporal overlapping between events.

### ISSUE THREAD

**Issue by hughplay** [leonnnop/VAR#3]
Thanks for sharing the code and the data of this interesting work.

I have a question after checking some samples in `var_*_v1.0.json`. The target of VAR is to infer the explanation from the incomplete observations. That is to say, the video content of the "explanation" event should not be exposed to models, am I right? However, it seems there exists temporal overlapping between the "explanation" and "observation" events. For example, in the following sample, the index of the "explanation" event is 1, whose timestamp is `[3.09, 61,72]` while the timestamp of the next video clip is `[15.43, 55.24]`. Is this acceptable?

``` json
{
  "events": [
    {
      "video_id": "ehGHCYKzyZ8",
      "timestamp": [
        0,
        2.78
      ],
      "clip_idx": 0,
      "clip_tot": 6,
      "sentence": "The video starts with a title logo sequence.",
      "duration": 61.72
    },
    {
      "video_id": "ehGHCYKzyZ8",
      "timestamp": [
        3.09,
        61.72
      ],
      "clip_idx": 1,
      "clip_tot": 6,
      "sentence": "A man and woman are in a living room demonstrating exercises.",
      "duration": 61.72
    },
    {
      "video_id": "ehGHCYKzyZ8",
      "timestamp": [
        15.43,
        55.24
      ],
      "clip_idx": 2,
      "clip_tot": 6,
      "sentence": "The woman lays on the ground.",
      "duration": 61.72
    },
    {
      "video_id": "ehGHCYKzyZ8",
      "timestamp": [
        17.59,
        54
      ],
      "clip_idx": 3,
      "clip_tot": 6,
      "sentence": "The man starts pointing to different areas of the woman's body as she does an exercise.",
      "duration": 61.72
    },
    {
      "video_id": "ehGHCYKzyZ8",
      "timestamp": [
        39.81,
        54.62
      ],
      "clip_idx": 4,
      "clip_tot": 6,
      "sentence": "The woman begins to do small sit ups.",
      "duration": 61.72
    },
    {
      "video_id": "ehGHCYKzyZ8",
      "timestamp": [
        56.47,
        61.72
      ],
      "clip_idx": 5,
      "clip_tot": 6,
      "sentence": "The woman ends with a final title logo sequence.",
      "duration": 61.72
    }
  ],
  "hypothesis": 1,
  "split": "train"
}
```

**Comment by leonnnop** [comment]
Thanks for your interest in VAR.

> ... It seems there exists temporal overlapping between the "explanation" and "observation" events, ... is this acceptable?

Yes, this is acceptable behavior in our cases, i.e., visual captioning. 

VAR, as a task, is mainly interested in two abilities of machine intelligence: First, the ability to reason beyond observations; Second, the ability to understand sequential or hierarchical visual events and present them with natural languages. 

The long-span events would deliver the general description of the global information while the short-span events supply details of local content. Filling in the inferable blank for missing local/global events would still be valuable cases for examining the second ability. For this reason, we opt to retain some hierarchical samples in the dataset.

**Comment by hughplay** [comment]
OK, I understand. Thanks for your response.
