### ISSUE TITLE
Some datas are wired.

### ISSUE THREAD

**Issue by LemonQC** [leonnnop/VAR#8]
Some examples are in the same video, while there is a lot of overlap.  E.g., the start time of the second event is in the time space of the first event. 

![image](https://user-images.githubusercontent.com/30914380/191512339-5475c066-0bc9-49bb-bbbe-3d41bb4ba74d.png)

**Comment by leonnnop** [comment]
The overlap you observed in the examples is expected and addressed in issue #4. Please refer to that issue for a detailed explanation.

**Comment by leonnnop** [comment]
Please also refer to issue #3 for a detailed discussion.
